"""Guardian agents: Risk, Legal & Compliance, Data & Analytics, Critic."""

from __future__ import annotations

import json
from typing import Literal

from pydantic import BaseModel, ConfigDict

from av_nexus.agents.base import AgentContext, AgentResult, BaseAgent
from av_nexus.agents.scout import as_string
from av_nexus.agents.util import as_number, confidence_from_sources

LEGAL_DISCLAIMER = (
    "This analysis is generated by an AI system and is not a substitute for qualified "
    "legal professionals or legal advice. Any compliance conclusion must be reviewed "
    "by a licensed attorney before action."
)


class CriticReviewSchema(BaseModel):
    """Independent-review reasoning a real model provider must produce in valid form."""

    model_config = ConfigDict(extra="forbid")

    verdict: Literal["PASS", "PASS WITH CAVEATS", "CHALLENGED"]
    issues: list[str]


class CriticOutputSchema(BaseModel):
    """Full published Critic output: deterministic metadata plus validated issues."""

    model_config = ConfigDict(extra="ignore")

    verdict: str
    issues: list[str]
    reviewed_confidence: float


class RiskAgent(BaseAgent):
    agent_id = "risk"
    name = "Chief Risk Officer"
    role = "Risk identification & rating"
    description = "Financial, market, operational, technology, reputation, strategic risk."
    capabilities = ["risk_analysis", "scenario_analysis"]
    tools = []
    permissions = ["research"]

    async def run(self, ctx: AgentContext, goal: str) -> AgentResult:
        raw = ctx.inputs.get("risks") or []
        entries = []
        for r in raw:
            if not isinstance(r, dict):
                continue
            level = level_from_score(as_number(r.get("risk_score"), 50.0))
            entries.append(
                {
                    "category": r.get("category", "market"),
                    "title": r.get("title", r.get("name", "")),
                    "level": level,
                    "mitigation": r.get("mitigation", ""),
                }
            )
        if not entries:
            cap = min(as_number(ctx.inputs.get("capital")), 100)
            entries.append(
                {
                    "category": "financial",
                    "title": "Capital at risk",
                    "level": level_from_score(cap),
                    "mitigation": "Stage capital deployment; require approvals",
                }
            )
        critical = [e for e in entries if e["level"] in ("HIGH", "CRITICAL")]
        return AgentResult.deterministic(
            result={
                "risk_matrix": entries,
                "overall_level": (
                    "CRITICAL"
                    if any(e["level"] == "CRITICAL" for e in entries)
                    else "HIGH"
                    if critical
                    else next((e["level"] for e in entries if e["level"] == "MEDIUM"), "LOW")
                ),
                "critical_risks": critical,
                "appetite_note": "Level-4 decisions require Chairman sign-off.",
            },
            confidence=confidence_from_sources(max(len(entries), 2)),
            assumptions=["Risk inputs supplied during research"],
            sources=["internal heuristic: risk rating"],
            risks=["Risk model is provisional until live monitoring"],
            next_recommended_agents=["critic", "legal_compliance"],
        )


class LegalComplianceAgent(BaseAgent):
    agent_id = "legal_compliance"
    name = "Legal & Compliance"
    role = "Compliance screening"
    description = "Identifies legal, privacy, contract and compliance risks."
    capabilities = ["compliance_review", "risk_screening"]
    tools = []
    permissions = ["research"]

    async def run(self, ctx: AgentContext, goal: str) -> AgentResult:
        sector = as_string(ctx.inputs.get("sector")) or "general"
        data_subjects = bool(ctx.inputs.get("processes_personal_data"))
        flags = []
        if data_subjects:
            flags.append("Privacy obligations (GDPR/CCPA-class) on personal data")
        if "financ" in sector or "bank" in sector:
            flags.append("Financial services licensing and AML considerations")
        if "health" in sector:
            flags.append("Healthcare data / device regulatory review required")
        if "space" in sector or "defense" in sector:
            flags.append("Export control and sector licensing review required")
        if not flags:
            flags.append("General commercial contracts + terms review recommended")

        return AgentResult.deterministic(
            result={"flags": flags, "disclaimer": LEGAL_DISCLAIMER},
            confidence=confidence_from_sources(1),
            assumptions=["Compliance screening is heuristic and non-exhaustive"],
            sources=["internal template: sector flags"],
            risks=["AI cannot replace licensed counsel; engagement required for real deals"],
            next_recommended_agents=["risk", "critic"],
        )


class DataAnalyticsAgent(BaseAgent):
    agent_id = "data_analytics"
    name = "Data & Analytics"
    role = "Metrics analysis & anomaly detection"
    description = "Dashboards for revenue, growth, customers, retention; anomaly alerts."
    capabilities = ["metrics_analysis", "anomaly_detection"]
    tools = []
    permissions = ["research"]

    async def run(self, ctx: AgentContext, goal: str) -> AgentResult:
        series = ctx.inputs.get("metrics_series") or {}
        anomalies = []
        for key, values in series.items():
            if not isinstance(values, list) or len(values) < 3:
                continue
            nums = [as_number(v) for v in values]
            mean = sum(nums) / len(nums)
            for i, v in enumerate(nums):
                if v < mean * 0.5 or v > mean * 1.8:
                    anomalies.append(
                        {"metric": key, "index": i, "value": v, "mean": round(mean, 2)}
                    )
        return AgentResult.deterministic(
            result={
                "dashboard_modules": [
                    "revenue",
                    "growth",
                    "customers",
                    "retention",
                    "marketing",
                    "operations",
                    "finance",
                ],
                "anomalies": anomalies,
            },
            confidence=confidence_from_sources(len(series)),
            assumptions=["Metrics supplied by tracking integrations"],
            sources=["internal heuristic: mean ± bounds"],
            risks=["No live pipeline configured in Phase 1"],
            next_recommended_agents=["ceo", "finance"],
        )


class CriticAgent(BaseAgent):
    agent_id = "critic"
    name = "Critic"
    role = "Independent reviewer"
    description = (
        "Refuses to rubber-stamp. Questions assumptions, missing data, failure modes, "
        "opposite conclusions, and bias."
    )
    capabilities = ["critical_review", "bias_detection"]
    tools = []
    permissions = ["research", "review"]

    async def run(self, ctx: AgentContext, goal: str) -> AgentResult:
        target = ctx.inputs.get("under_review") or {}
        if not isinstance(target, dict):
            target = {}
        confidence = as_number(target.get("confidence"), 0.0)
        merged = target.get("result") or {}

        system_prompt = (
            "You are the Critic: an independent reviewer that refuses to rubber-stamp. "
            "Question assumptions, missing data, failure modes, opposite conclusions, bias "
            "and over-claiming. Base every issue ONLY on the supplied review payload. "
            "Respond ONLY with a JSON object exactly matching this schema: "
            + json.dumps(CriticReviewSchema.model_json_schema())
        )
        user_prompt = json.dumps(
            {
                "goal": goal,
                "reviewed_confidence": confidence,
                "reviewed_stage_results": merged,
            },
            default=str,
        )

        review = self._structured_llm(ctx, system_prompt, user_prompt, CriticReviewSchema)
        if review is None:
            return AgentResult.deterministic(
                result={
                    "verdict": "NOT_REVIEWED",
                    "issues": [],
                    "reviewed_confidence": confidence,
                    "reasoning": {"status": "not_generated", "reason": "no_llm_provider"},
                },
                confidence=0.35,
                assumptions=["Independent review requires a model provider"],
                sources=["none available"],
                risks=["The combined assessment went unreviewed by the Critic"],
                next_recommended_agents=["validation", "risk"],
            )

        return AgentResult.llm(
            result={
                "verdict": review["verdict"],
                "issues": review["issues"],
                "reviewed_confidence": confidence,
            },
            schema=CriticOutputSchema,
            confidence=0.9 if review["issues"] else 0.7,
            assumptions=["Critique is grounded in the supplied stage results"],
            sources=["validated LLM critical review (real provider)"],
            risks=["Critic cannot detect all factual errors"],
            next_recommended_agents=["validation", "risk"],
        )


def level_from_score(score: float) -> str:
    if score >= 80:
        return "CRITICAL"
    if score >= 60:
        return "HIGH"
    if score >= 40:
        return "MEDIUM"
    return "LOW"
